# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql:8.0.36
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    links:
      - db

volumes:
  data:
